[features]
seeds = false
[programs.localnet]
solana_twitter = "6DAtUVDGwUrV5xEtRxyYXGG6kvskeFQuhDNyt7E38yhx"

[programs.devnet]
solana_twitter = "6DAtUVDGwUrV5xEtRxyYXGG6kvskeFQuhDNyt7E38yhx"

# TODO - We would probably use a different keypair for mainnet cluster in future
[programs.mainnet]
solana_twitter = "6DAtUVDGwUrV5xEtRxyYXGG6kvskeFQuhDNyt7E38yhx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/zachboerger/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
silly-echo = "echo 'Hello from ZBR!'"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
